/*
 * constantes.c
 *
 *  Created on: 17/10/2017
 *      Author: utnso
 */

// Tipos de mensajes para el protocolo de comunicación
enum tiposMensajes {
	EN_DESUSO, //00
	TIPO_MSJ_TABLA_TRANSFORMACION, //01
	TIPO_MSJ_TABLA_REDUCCION_LOCAL, //02
	TIPO_MSJ_TABLA_REDUCCION_GLOBAL, //03
	TIPO_MSJ_TABLA_ALMACENAMIENTO_FINAL, //04
	TIPO_MSJ_ERROR, //05
	TIPO_MSJ_OK, //06
	TIPO_MSJ_HANDSHAKE, //07
	TIPO_MSJ_HANDSHAKE_RESPUESTA_OK, //08
	TIPO_MSJ_HANDSHAKE_RESPUESTA_DENEGADO, //09
	TIPO_MSJ_PATH_ARCHIVO, //10
	TIPO_MSJ_PATH_ARCHIVO_TRANSFORMAR, //11
	TIPO_MSJ_PEDIDO_METADATA_ARCHIVO, //12
	TIPO_MSJ_METADATA_ARCHIVO, //13
	TIPO_MSJ_DATOS_CONEXION_NODOS, //14
	TIPO_MSJ_TRANSFORMACION_OK, //15
	TIPO_MSJ_TRANSFORMACION_ERROR, //16
	TIPO_MSJ_REDUCC_LOCAL_OK, //17
	TIPO_MSJ_REDUCC_LOCAL_ERROR, //18
	TIPO_MSJ_REDUCC_GLOBAL_OK, //19
	TIPO_MSJ_REDUCC_GLOBAL_ERROR, //20
	TIPO_MSJ_ALM_FINAL_OK, //21
	TIPO_MSJ_ALM_FINAL_ERROR, //22
	TIPO_MSJ_FINALIZAR_JOB, //23
	TIPO_MSJ_ABORTAR_JOB, //24
	TIPO_MSJ_DATANODE, //25
	TIPO_MSJ_ARCHIVO, //26
	TIPO_MSJ_PEDIR_BLOQUES, //27
	TIPO_MSJ_BLOQUE_DESDE_DATANODE, //28
	TIPO_MSJ_DATA_TRANSFORMACION_WORKER, //29
	TIPO_MSJ_DATA_REDUCCION_LOCAL_WORKER, //30
	TIPO_MSJ_DATA_REDUCCION_GLOBAL_WORKER, //31
	TIPO_MSJ_WORKER_ALMACENAMIENTO_FINAL //32
};

// OJO! Si se agrega algo en el enum de arriba actualizar dejar siempre acá el último valor del array
const int protocoloCantidadMensajes[TIPO_MSJ_WORKER_ALMACENAMIENTO_FINAL + 1] = {
		0, //00
		1, //01
		1, //02
		1, //03
		1, //04
		0, //05
		0, //06
		1, //07
		0, //08
		0, //09
		1, //10
		1, //11
		1, //12
		1, //13
		1, //14
		2, //15
		2, //16
		1, //17
		1, //18
		1, //19
		1, //20
		0, //21
		0, //22
		0, //23
		0, //24
		4, //25
		3, //26
		1, //27
		1, //28
		4, //29
		2, //30
		2, //31
		2  //32
};

const char* protocoloMensajesPredefinidos[TIPO_MSJ_WORKER_ALMACENAMIENTO_FINAL + 1] = {
		"EN_DESUSO",
		"TABLA_TRANSFORMACION",
		"TABLA_REDUCCION_LOCAL",
		"TABLA_REDUCCION_GLOBAL",
		"TABLA_ALMACENAMIENTO_FINAL",
		"ERROR",
		"OK",
		"HANDSHAKE",
		"HANDSHAKE_RESPUESTA_OK",
		"HANDSHAKE_RESPUESTA_DENEGADO",
		"PATH_ARCHIVO",
		"PATH_ARCHIVO_TRANSFORMAR",
		"PEDIDO_METADATA_ARCHIVO",
		"METADATA_ARCHIVO",
		"DATOS_CONEXION_NODOS",
		"TRANSFORMACION_OK",
		"TRANSFORMACION_ERROR",
		"REDUCC_LOCAL_OK",
		"REDUCC_LOCAL_ERROR",
		"REDUCC_GLOBAL_OK",
		"REDUCC_GLOBAL_ERROR",
		"ALM_FINAL_OK",
		"ALM_FINAL_ERROR",
		"FINALIZAR_JOB",
		"ABORTAR_JOB",
		"DATANODE",
		"ARCHIVO",
		"PEDIR_BLOQUES",
		"BLOQUE_DESDE_DATANODE",
		"DATA_TRANSFORMACION_WORKER",
		"DATA_REDUCCION_LOCAL_WORKER",
		"DATA_REDUCCION_GLOBAL_WORKER",
		"WORKER_ALMACENAMIENTO_FINAL"
};
